from main_app.models import Skill,Employee
t = Skill(skill='c',field='IT')
t.save()
t = Skill(skill='c++',field='IT')
t.save()
t = Skill(skill='java',field='IT')
t.save()
t = Skill(skill='python',field='IT')
t.save()
t = Skill(skill='git',field='IT')
t.save()
t = Skill(skill='html',field='IT')
t.save()
t = Skill(skill='english',field='Communication')
t.save()
t = Skill(skill='spanish',field='Communication')
t.save()
t = Skill(skill='french',field='Communication')
t.save()
t = Skill(skill='Dutch',field='Communincation')
t.save()
t = Skill(skill='frontend',field='IT')
t.save()
t = Skill(skill='Backend',field='IT')
