from main_app.models import Skill,Employee
t = Skill(skill='c',field='IT')
t.save()
t = Skill(skill='c++',field='IT')
t.save()
t = Skill(skill='java',field='IT')
t.save()
t = Skill(skill='python',field='IT')
t.save()
t = Skill(skill='git',field='IT')
t.save()
t = Skill(skill='html',field='IT')
