# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='number_position',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
